### PR TITLE
Delete all of your work

### PR DESCRIPTION
**Pull request by erickzhao**
Tested on Firefox Developer Edition 67.0b13 (64-bit)

macOS Mojave 10.14.3 (18D109)

### CODE REVIEW

**Review by sulemanmalik — APPROVED** [review]
this is phenomenal!! great work @erickzhao you've done it again

**Comment by erickzhao** [comment]
@boggy-d please advise my PR has been open for like 2 months now

**Review by pepoandra — APPROVED** [review]
good stuff

**Comment by boggy-d** [comment]
due to popular demand, this feature will be implemented into master

**Pull request merged**
